image: alpine/edge
packages:
  - rust
  - cargo
sources:
  - https://git.sr.ht/~int80h/gemserv
tasks:
  - build: |
        cd gemserv/
        cargo build
triggers:
  - action: email
    condition: failure
    to: "<int@80h.dev>"
